import { Geist, Geist_Mono } from "next/font/google";
import Footer from "./components/Footer";
import "./globals.css";
import { ReactNode } from "react";

// Configure custom Google fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next.js Testing App",
  description: "Generated by create next app",
};

// Define strict types for RootLayout properties
interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      {/* Flexbox layout ensures the footer always sticks to the bottom of the screen */}
      <body style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column', margin: 0 }}>
        
        {/* Main page content wrapper */}
        <div style={{ flex: 1 }}>
          {children}
        </div>

        {/* Centralized global footer component */}
        <Footer />
        
      </body>
    </html>
  );
}